# Generated by Django 2.0.1 on 2018-02-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0015_auto_20180207_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('cname', models.CharField(blank=True, max_length=12, null=True)),
                ('cfname', models.CharField(blank=True, max_length=24, null=True)),
                ('ename', models.CharField(blank=True, max_length=24, null=True)),
                ('efname', models.CharField(blank=True, max_length=48, null=True)),
                ('othername', models.CharField(blank=True, max_length=24, null=True)),
                ('avatar', models.ImageField(default='static/upload/avatar/defult.jpg', upload_to='static/upload/avatar', verbose_name='头像')),
                ('describe', models.CharField(blank=True, max_length=128, null=True, verbose_name='签名')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('famous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctree.Celebrity')),
            ],
        ),
    ]
