# Generated by Django 2.0.1 on 2018-02-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0016_celebrity_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='avatar',
            field=models.ImageField(default='/static/upload/avatar/defult.jpg', upload_to='static/upload/avatar', verbose_name='头像'),
        ),
    ]
