# Generated by Django 2.0.1 on 2018-02-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0017_auto_20180209_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='avatar',
            field=models.ImageField(default='/static/defult.jpg', upload_to='static/upload/avatar', verbose_name='头像'),
        ),
    ]
