# Generated by Django 2.0.1 on 2018-02-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0018_auto_20180209_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='avatar',
            field=models.ImageField(default='defult.jpg', upload_to='static/upload/avatar', verbose_name='头像'),
        ),
    ]
