# Generated by Django 2.0.1 on 2018-02-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0022_auto_20180209_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='avatar',
            field=models.ImageField(default='avatar/defult.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
