# Generated by Django 2.0.1 on 2018-02-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0025_auto_20180212_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='avatar',
            field=models.ImageField(default='defult.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
